version: "3.8"

services:
  zomboid-server:
    build: .
    image: laurigates/zomboid-server
    environment:
      ADMINPASS: "changeme"
      SERVERNAME: "MyServer"
    volumes:
      - ./Zomboid:/home/steam/Zomboid
    ports:
      - 8766:8766/udp
      - 8767:8767/udp
      - 16261:16261/udp
      - 16262-16272:16262-16272
      - 27015:27015
    restart: unless-stopped
